### ISSUE TITLE
do you train your online tracker without public detection?

### ISSUE THREAD

**Issue by chenrxi** [songguocode/TADAM#3]
Have you ever trained your online tracker without public detection? If so, how to detect new track in private detector mode and distinguish from the track already existed successfully. Also, looking forward to your code and models available and thanks a lot for your great job.

**Comment by songguocode** [comment]
It is trained in a way similar to training a Faster-RCNN detector, while the rpn is discarded during tracking and RoIs are provided by public detections. It does not actively detect new targets, but refines positions of existing tracked targets given earlier information. A new target is only initiated with a public detection that is not covered by existing targets. Hope this clarifies your questions.
