### ISSUE TITLE
Test on video

### ISSUE THREAD

**Issue by Moaz-Morsy** [songguocode/TADAM#4]
how to test these models on .mp4 video without training the models?
what are the steps?

**Comment by songguocode** [comment]
Hi, the code is for testing is designed for videos from the MOTChallenge dataset to be image sequence format. For example, the test sequence MOT17-01-FRCNN video sequence contains frames 000001.jpg, 000002.jpg, etc. If testing on a random .mp4 video, it is necessary to convert the video into images first. Then, it requires modification on data loading, as the code currently only supports MOT dataset. You need to build a `lib\dataset\new_dataset.py` similar to the `lib\dataset\mot.py`, and import in related files. Hope this helps!

**Comment by Moaz-Morsy** [comment]
how about taking live data (images) from camera ? for a self driving car project
will i need to adjust "lib\dataset\mot.py"  same as  mp4?

**Comment by songguocode** [comment]
While it is possible to take live data (build a similar data loader format as you mentioned), you may need extra code for capturing images and processing them. Moreover, this project is specialized for the public detection (given by existing detectors) and may not be suitable for a self driving car project. I would recommend do some search on more efficient live private multi-object trackers.

**Comment by songguocode** [comment]
There are tracking datasets more related to self driving, such as [nuScenes](https://www.nuscenes.org/) and [KITTI-360](http://www.cvlibs.net/datasets/kitti-360/). You can check their leaderboards for the best performing algorithms.

**Comment by wassimea** [comment]
This would be extremely useful. I found the current implementation too heavily reliant on config files and paths that it makes implementing a method that just does inference on a video clip too cumbersome.
