### ISSUE TITLE
Testing: Low FPS

### ISSUE THREAD

**Issue by hoonkai** [songguocode/TADAM#6]
Hi

Great work. I've been running test_tracker but I'm getting <2FPS on average. Is there any particular reason why it's rather slow? It's likely not bounded by GPU as the utilisation is rather low. The CPU isn't much utilised either.

Any advice appreciated.

**Comment by songguocode** [comment]
That’s normal when we have larger number of identities. As the focus of the project is not on the speed, not much optimization has been carried out, such as speeding up attention computation. If you are seeking a faster tracker, please consider ones take speed into account, like FairMOT. How this helps.

**Comment by hoonkai** [comment]
> That’s normal when we have larger number of identities. As the focus of the project is not on the speed, not much optimization has been carried out, such as speeding up attention computation. If you are seeking a faster tracker, please consider ones take speed into account, like FairMOT. How this helps.

Thanks!

**Comment by hoonkai** [comment]
@songguocode Just curious, how would you compare your work with FairMOT? IIRC their accuracy and precision are quite high.

**Comment by songguocode** [comment]
FairMOT uses private detection and addresses more on detection design, while TADAM focuses on bringing synergy by adopting attention and uses provided public detections. Different goals lead to various designs.
