### ISSUE TITLE
Can't find the dataset error

### ISSUE THREAD

**Issue by Jonyond-lin** [songguocode/TADAM#7]
Hi, thanks for your excellent work. Unfortunately I ran into the problems below：

No such file or directory: 'datasets/MOT17/MOT17Det/train'

Could you please help me find what's wrong with it？
![error](https://user-images.githubusercontent.com/36891952/130547003-178bf666-b84e-476a-9bcd-99662ab09e5c.png)

**Comment by songguocode** [comment]
Please follow step 5 and modify the config file to pass dataset path

**Comment by LiangXiaoguo** [comment]
Thank you very much for your excellent. May I ask how to obtain the test result of the dataset corresponding to the test sequence instead of the evaluation result

**Comment by songguocode** [comment]
Please note that only we can only obtain results for datasets with ground truth provided. For MOTChallenge test sequences, it is necessary to register on their [website](https://motchallenge.net/) and upload the generated tracking data, then wait for email results.
